# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .net package publish to nuget

on:
  push:
    branches: [ "beta", "release" ]
  pull_request:
    branches: [ "beta", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --output ./packages --no-build --no-restore
    - name: Push
      env:
        api_secret: ${{ secrets.NUGET_PUBLISH_SECRET }}
      run: |
        dotnet nuget push ./packages/am.kon.packages.services.kafka.*.nupkg --api-key "$api_secret" --source https://api.nuget.org/v3/index.json --skip-duplicate
